name: Build and Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    # ↓ ----- このブロックを追加 ----- ↓
    permissions:
      contents: write
    # ↑ --------------------------- ↑
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in the dist directory
        run: |
          echo "Listing files in the dist directory for ${{ runner.os }}..."
          ls -R dist

      # (以下、アップロードステップは変更なし)
      - name: Upload macOS Release Assets
        if: runner.os == 'macOS'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.zip
            dist/*-mac.yml

      - name: Upload Windows Release Assets
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*-win.yml